name: Google Calendar Invitee Reminder

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  send_reminders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Calendar Invitee Reminder Script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        ORGANIZER_EMAIL: ${{ secrets.ORGANIZER_EMAIL }}
        ORGANIZER_NAME: ${{ secrets.ORGANIZER_NAME }}
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
        python invitee_reminder.py
